### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lukasbestle** [mzur/kirby-defuse-session#1]
Thanks for creating this plugin, it will be very helpful for developers.

A bit of feedback: Instead of overriding the App instance with a monkey patched session instance, you could use a custom session store like the [`TestSessionStore` we use for our unit tests](https://github.com/k-next/kirby/blob/master/tests/Session/mocks.php). You should be able to inject your own class instance at runtime by setting it as the session root (yes, set an object as the root!).

**Comment by mzur** [comment]
Thanks for the feedback, that sounds like a much better solution. I didn't really grok whats going on there with the SessionStore, SessionData, Sessions or AutoSession, to be honest. But I did wonder why my tests using the session failed and yours didn't.

**Comment by lukasbestle** [comment]
If you have any questions, feel free to get in touch. :)

**Comment by mzur** [comment]
I tried to implement your suggestion (see f9831114420caa0dfe8113281c6a02defc0a603a). However, I did not find a way to modify the session root for an existing `App` instance. I still had to [create a new instance](https://github.com/mzur/kirby-defuse-session/blob/f9831114420caa0dfe8113281c6a02defc0a603a/src/Defuse.php). Then I found that replacing the session store did not solve the original problem. With this approach, the session class still sets a cookie/header which [breaks the tests](https://travis-ci.org/mzur/kirby-defuse-session/builds/415549023). Maybe you can elaborate on how you solve this in your tests?

The goals of this plugin are:

1. Tests using the session should run without hanging or throwing `Cannot modify header information - headers already sent...`.
2. Tests using the session should not create any files.

**Comment by lukasbestle** [comment]
You are right, the `roots` object can't be modified after it has been created, which actually makes a lot of sense.
The best way would probably be to inject the object before the tests even start running (for example in a test bootstrap file) so that the root is set before the App object is first created. But your implementation should actually be alright for most use-cases.

> Then I found that replacing the session store did not solve the original problem. With this approach, the session class still sets a cookie/header which breaks the tests. Maybe you can elaborate on how you solve this in your tests?

Oh, right!

But for some reason, our tests don't fail even though a cookie is being set. Also I've tried pulling down your repo and running the tests. They run in about 120 ms without any errors. No idea why Travis doesn't like the setup.

**Comment by mzur** [comment]
> The best way would probably be to inject the object before the tests even start running

How would you do that?

> No idea why Travis doesn't like the setup.

My machine doesn't like it either. You can use the PHPUnit Docker image to reproduce this (it hangs):

```bash
docker run -v $(pwd):/app --rm phpunit/phpunit tests
```

**Comment by lukasbestle** [comment]
Well, you need to create an `App` object with the custom root from a bootstrap file (which you can configure in PHPUnit's config). But now that I think about it, actually there is no huge advantage over your solution. So your solution is actually quite good because it is so simple.

> My machine doesn't like it either. You can use the PHPUnit Docker image to reproduce this (it hangs):

I'm currently not on a machine with Docker installed, so unfortunately I can't test it at the moment. But it's very strange given that the Kirby tests also run on Travis and don't have this issue.

**Comment by mzur** [comment]
> But it's very strange given that the Kirby tests also run on Travis and don't have this issue

Yeah, I thought that, too. I think I won't change the current code of the plugin. Not having to replace the app instance would have been nice but isn't possible as it seems.

**Comment by lukasbestle** [comment]
What you could do is to base your implementation on the `Session` class instead of on `AutoSession`, because the `Session` class can be configured not to use cookies at all. But as you would have to replace the App instance for this as well, the only advantage would be that the native session code is used instead of your mock class. But as your mock has most of the features you would need in a plugin unit-test, that is probably not worth it. :)
